application: rfvio-1257
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)
- url: /files/(.*)
  static_files: static/files/\1
  upload: static/files/(.*)
- url: /.*
  script: main.app